name: Build and test with Docker

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker
      uses: docker://docker:stable
    - name: Build and push Docker image
      run: |
        docker build -t excite-image .
        docker push excite-image
        #- name: Run Docker container
        #run: |
        #docker run -it excite-image /bin/bash

